INPUT_DIR: '/home/alan/Downloads/style_transfer'
OUTPUT_DIR: '/home/alan/Downloads/style_transfer/LST/SPN'
MODEL_DIR: '/home/alan/Downloads/style_transfer'
MODEL:
    NAME: 'LST'
    ENCODER_NAME: ('lst', 'vgg_r41', 'vgg_r51')
    DECODER_NAME: ('lst', 'lst_dec_r41')
    LST:
        LAYER: 'r41'
        MATRIX_SIZE: 32
        STYLE_LAYERS: ("r11","r21","r31","r41")
        CONTENT_LAYERS: 'r41'
        STYLE_WEIGHT: 0.02
        CONTENT_WEIGHT: 1.
        SPN_NUM: 1
        DISABLE_TRANSFER: True
        LOAD_LOSS_NET: False
        DISABLE_SPN: False
OPTIMIZER:
    BASE_LR: 1e-3
    MAX_ITER: 100000
DATALOADER:
    BATCH_SIZE: 9
    NUM_WORKERS: 4
DATASET:
    TRAIN: 'coco_artwiki_style_train'
DEVICE: 'cuda:0'
INPUT: 
    FINE_SIZE: 512